Main svc
avan-es/java-explore-with-me pull request #4
Opened 2023-05-13 18:22 UTC by avan-es

2023-05-22 09:29 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-05-22 09:29 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +    @Transactional
А почему `Transactional` только на этом методе, а не на классе целиком. `Readonly` транзакции тоже нужны, чтобы данные не могли поменяться в процессе выполнения запроса

2023-05-22 09:29 UTC, LexLippi commented on stats/stats-dto/src/main/java/ru/practicum/dto/ViewStats.java
> +    }
Зачем, если у тебя есть `AllArgsConstructor`?

2023-05-22 09:29 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    private String serverUrl = "http://stats-server:9090";
Лучше `java.net.URI` использовать, а не `String`

2023-05-22 09:29 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    private String serverUrl = "http://localhost:9090";*/
Удалить этот коммент

2023-05-22 09:29 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    private final String end = "2100-01-01 00:00:00";
Исходя из чего и зачем эти константы выбраны?

2023-05-22 09:29 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/category/repository/CategoryRepository.java
> +            "LIMIT 1", nativeQuery = true)
Вместо `limit` лучше использовать оператор `fetch`, так как `limit` не определен в стандарте, и реализует его та или иная СУБД, это лишь вопрос желания ее авторов, а мы хотим иметь возможномть переходить между СУБД с наименьшими затратами:

https://www.commandprompt.com/education/how-to-use-fetch-clause-in-postgresql/

2023-05-22 09:29 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/category/service/adminPart/CategoryAdminServiceImpl.java
> +@Transactional(readOnly = true)
Зачем `readonly` - `true`, если нет ни одного метода на чтение?

2023-05-22 09:29 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/compilation/service/adminPart/CompilationAdminServiceImpl.java
> +@Transactional(readOnly = true)
Зачем `readOnly = true`?

2023-05-22 11:57 UTC, avan-es commented on stats/stats-server/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +    @Transactional
Спасибо! Исправил!

2023-05-22 12:12 UTC, avan-es commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    private String serverUrl = "http://stats-server:9090";
Готово

2023-05-22 12:12 UTC, avan-es commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    private String serverUrl = "http://localhost:9090";*/
Готово)

2023-05-22 12:32 UTC, avan-es commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    private final String end = "2100-01-01 00:00:00";
У нас в StatisticController обязательные параметры запроса для поиска просмотров (по первому этапу диплома) : с какой даты и по какую искать просмотры (hit) в БД статистики. А в main-service мы выгружаем общее количество просмотров для EventFuul и ShortDTO. Поэтому параметры start и end не задаём. Я сделал тут Default значения для них (т.к. в статистики идет проверка времени, и дефолтных значений в них нет (по ТЗ 1 этапа). 

Но согласен - название не информативное.

Переделал. Переименовал start -> viewsFromThisDate

переменную end удалил. Вместо неё в параметрах добавляю текущую дату: LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))

2023-05-22 12:40 UTC, avan-es commented on main-service/src/main/java/ru/practicum/category/repository/CategoryRepository.java
> +            "LIMIT 1", nativeQuery = true)
Исправил! Спасибо за ссылку)

2023-05-22 12:56 UTC, avan-es commented on main-service/src/main/java/ru/practicum/category/service/adminPart/CategoryAdminServiceImpl.java
> +@Transactional(readOnly = true)
Поправил)

2023-05-22 13:22 UTC, avan-es commented
Привет! Всё подправил )

2023-05-23 07:10 UTC, LexLippi requested changes
Привет!

Осталась пара совсем мелких замечаний!

Желаю удачи!

2023-05-23 07:10 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/compilation/service/adminPart/CompilationAdminServiceImpl.java
> +        Compilation compilationOld = compilationUtils.getCompilationById(compId);
странное название

2023-05-23 07:10 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/compilation/service/adminPart/CompilationAdminServiceImpl.java
> +        }
А почему выше через `Optional`, а здесь через условный оператор? Одно и тоже действие же происходит

2023-05-23 07:10 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    private URI serverUrl = URI.create("http://stats-server:9090");
Это поле разве не `final`?

2023-05-23 07:10 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +                        LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
`formatter` стоит завести константный один на весь проект. Чтобы каждый раз не копировать, а то так можно случайно в разных местах разный формат получить

2023-05-23 12:37 UTC, avan-es commented on main-service/src/main/java/ru/practicum/compilation/service/adminPart/CompilationAdminServiceImpl.java
> +        }
Исправил

2023-05-23 13:06 UTC, avan-es commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +        ResponseEntity<Object[]> response = restTemplate.getForEntity(path, Object[].class);
Круто! Спасибо!!! Теперь в одну строчку 😎

2023-05-23 13:28 UTC, avan-es commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +                        LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
Сделал класс DateConstants в stats-dto (он доступен всем модулям уже), завел там DateTimeFormatter и DATE_PATTERN! Спасибо!

2023-05-24 08:00 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-05-24 12:46 UTC, merged