feat: фича комментарии
avan-es/java-explore-with-me pull request #5
Opened 2023-05-27 18:25 UTC by avan-es

2023-05-29 07:46 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть одно маленькое замечание, и вопрос.

Желаю удачи!

2023-05-29 07:46 UTC, LexLippi commented on main-service/src/main/resources/schema.sql
> +    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY              NOT NULL,
Здесь нет необходимости в `NOT NULL`

2023-05-29 07:46 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/comment/service/privatePart/CommentPrivServiceImpl.java
> +        commentUtils.checkIfUserAlreadyPostComment(userId, eventId);
А в ТЗ требуется такая проверка?
Просто немного странно, что пользователь не может оставить два комментария к событию.

2023-05-29 17:03 UTC, avan-es commented on main-service/src/main/resources/schema.sql
> +    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY              NOT NULL,
Исправил)

2023-05-29 17:08 UTC, avan-es commented on main-service/src/main/java/ru/practicum/comment/service/privatePart/CommentPrivServiceImpl.java
> +        commentUtils.checkIfUserAlreadyPostComment(userId, eventId);
Нет) ТЗ сами придумываем на фичу. Но согласен. Изначально я думал сделать, как отзыв к товару - купил - оставил отзыв. Но сейчас вижу, что лучше не ограничивать комментарии, на случай, если кому-то нужно будет ответить на вопрос или завяжется обсуждение. Убрал это ограничение) Спасибо!

2023-05-30 07:37 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Поздравляю с завершением курса Практикума, и желаю удачи в дальнейшем пути Java-разработчика.

2023-06-06 16:49 UTC, merged